version: '3.5'

services:
  app:
    container_name: 'findAMusician_backend'
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 8000
    ports:
      - '8000:8000'
    networks:
      - default
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: 'findAMusician_postgres'
    image: postgres:12.2
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
