/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/genres": {
    /** Get a list of all genres */
    get: operations["getGenres"];
  };
  "/group/invitation": {
    /** Invite a musician in a group */
    post: operations["inviteInAGroup"];
  };
  "/instruments": {
    get: operations["getInstruments"];
  };
  "/login": {
    post: operations["login"];
  };
  "/logout": {
    /** Logout the current user */
    delete: operations["logout"];
  };
  "/me": {
    /** Get the user connected information */
    get: operations["me"];
  };
  "/musician/{musicianId}": {
    patch: operations["patchMusician"];
  };
  "/musicians": {
    get: operations["getMusicians"];
  };
  "/refresh_token": {
    /** Send a new access token */
    post: operations["postRefreshToken"];
  };
  "/register": {
    post: operations["register"];
  };
}

export interface components {
  schemas: {
    musician: {
      id: string;
      email: string;
      givenName?: string;
      familyName?: string;
      phone?: string;
      facebookUrl?: string;
      twitterUrl?: string;
      instagramUrl?: string;
      promotion?: "L1" | "L2" | "L3" | "M1" | "M2";
      location?: "Douai" | "Lille";
      instruments?: components["schemas"]["instrument"][];
    };
    instrument: {
      id: string;
      name: string;
    };
    genre: {
      id: string;
      name: string;
    };
    token: {
      accessToken: string;
      refreshToken: string;
    };
    httpError: {
      msg: string;
      stack?: string;
    };
  };
}

export interface operations {
  /** Get a list of all genres */
  getGenres: {
    responses: {
      /** A list of all genres */
      200: {
        content: {
          "application/json": components["schemas"]["genre"][];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
  };
  /** Invite a musician in a group */
  inviteInAGroup: {
    responses: {
      /** The user has been invited */
      201: {
        content: {
          "application/json": string;
        };
      };
      /** The user is already invited */
      400: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
      /** User that invite doesn't have the access */
      401: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          groupId: string;
          musicianId: string;
          instrumentId: string;
        };
      };
    };
  };
  getInstruments: {
    responses: {
      /** A list of all the instruments */
      200: {
        content: {
          "application/json": components["schemas"]["instrument"][];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
  };
  login: {
    responses: {
      /** Login successful */
      200: {
        content: {
          "application/json": {
            token: components["schemas"]["token"];
            musician: components["schemas"]["musician"];
          };
        };
      };
      /** The user is not find */
      400: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
      /** invalid password */
      401: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          email?: string;
          password?: string;
        };
      };
    };
  };
  /** Logout the current user */
  logout: {
    responses: {
      /** All the token has been deleted */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
  };
  /** Get the user connected information */
  me: {
    responses: {
      /** The user information */
      200: {
        content: {
          "application/json": {
            musician: components["schemas"]["musician"];
            genres: components["schemas"]["genre"][];
            instruments: components["schemas"]["instrument"][];
          } & {
            password: unknown;
          };
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
  };
  patchMusician: {
    parameters: {
      path: {
        musicianId?: unknown;
      };
    };
    responses: {
      /** The musician information has been updated */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** user is unauthorized */
      403: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          email?: string;
          givenName?: string;
          familyName?: string;
          phone?: string;
          facebookUrl?: string;
          twitterUrl?: string;
          instagramUrl?: string;
          promotion?: "L1" | "L2" | "L3" | "M1" | "M2";
          location?: "Douai" | "Lille";
        };
      };
    };
  };
  getMusicians: {
    responses: {
      /** A list of all the musicians */
      200: {
        content: {
          "application/json": components["schemas"]["musician"][];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
  };
  /** Send a new access token */
  postRefreshToken: {
    responses: {
      /** a new access token */
      200: {
        content: {
          "application/json": {
            accessToken: string;
          };
        };
      };
      /** Invalid refresh token */
      401: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          refreshToken: string;
        };
      };
    };
  };
  register: {
    responses: {
      /** The user has been registered in the db */
      201: {
        content: {
          "application/json": {
            token?: components["schemas"]["token"];
            musician?: components["schemas"]["musician"];
            genres?: components["schemas"]["genre"][];
            instruments?: components["schemas"]["instrument"][];
          };
        };
      };
      /** Error intern server */
      500: {
        content: {
          "application/json": components["schemas"]["httpError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          musician: components["schemas"]["musician"];
          password: string;
          genres: components["schemas"]["genre"][];
          instruments: components["schemas"]["instrument"][];
        };
      };
    };
  };
}

export interface external {}
